stages:
  - test

test_job:
  stage: test
  image: debian
  before_script:
    - apt-get update
    - apt-get install
    - apt-get install -y curl
    - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
    - apt-get insall -y nodejs
  script:
    - npm install -g pnpm
    - pnpm install
    - pnpm prisma:generate
    - pnpm build:libs
    - pnpm install
    - pnpm test
