stages:
  - test

test_job:
  stage: test
  image: node
  script:
    - npm install -g pnpm
    - npm install -g prisma
    - pnpm install
    - pnpm prisma:generate
    - pnpm build:libs
    - pnpm install
    - pnpm test
